== Exo 21

Ajouter une validation pour que l'appel au endpoint POST /api/v1/pets
retourne un code 400 si le nom est vide ou si l'âge est inférieur à 0

La classe de test Exo21 de PetControllerTest doit passer sans y apporter de modifications

== Exo 22

Créer une meta annotation pour que les appels GET et PUT partagent la même règle de validation du petId dans l'url

Les classes de test Exo20 et Exo22 de PetControllerTest doivent passer sans y apporter de modifications

== Exo 23

Les "requests params" peuvent être groupés dans un objet.
Il ne faut pas lui ajouter d'annotation (même pas @RequestParam) sans lui fournir d'annotation.

Créer une classe AgeRange pour remplacer les paramètres de GET /api/v1/pets

La classe de test Exo23 de PetControllerTest doit passer sans y apporter de modifications

== Exo 24

Créer une annotation @ValidAgeRange pour valider que l'âge minimum est inférieur à l'âge maximum s'ils sont fournis

Les classes de test Exo23 et Exo24 de PetControllerTest doivent passer sans y apporter de modifications

== Exo 25

A l'aide d'un "controller advice", renvoyer une erreur 418 en cas d'exception ImATeapotException

La classe de test Exo25 de PetControllerTest doit passer sans y apporter de modifications

== Exo 26

Dans le controller advice ErrorHandler, qui étend la gestion des erreurs de spring,
remplacer le retour en cas d'erreur de validation par une réponse sous la forme:

[source,json]
----
{
  "status": 400,
  "message": "message de l'exception"
}
----

La classe de test Exo26 de PetControllerTest doit passer sans y apporter de modifications

== Exo 27

Ajouter le fichier src/main/resources/application.yml

[source,yml]
----
custom:
    app-name: "mon application"
    app-version: "1.0.1"
    git:
        branch: "main"
        commit: "123456"
----

Ajouter un fichier banner.txt dans src/main/resources avec le contenu

[source]
----
${custom.app-name} ${custom.app-version} ${custom.git.branch} ${custom.git.commit}
----

== Exo 28

En utilisant des @Value, créer un endpoint GET /api/v1/info qui renvoie la réponse suivante en json

[source,json]
----
{
    "app-name": "mon application",
    "app-version": "1.0",
    "git": {
        "branch": "master",
        "commit": "123456"
    }
}
----

La classe de test Exo28 de InfoTest doit passer sans y apporter de modifications

== Exo 29

Remplacer l'utilisation des @Value par un l'approche avec un @ConfigurationProperties

La classe de test Exo28 de InfoTest doit toujours passer sans y apporter de modifications

== Exo 30

Ajouter le fichier src/main/resources/application-dev.yml

[source,yml]
----
custom:
    app-version: "1.0.2-SNAPSHOT"
    git:
        branch: "feature/TICKET"
        commit: "654321"
----

La classe de test Exo30 de InfoTest doit passer sans y apporter de modifications

== Exo 31

Ajouter un paramètre variable "maxRange" dans l'annotation @ValidAgeRange.
Modifier la validation pour garantir que l'écart entre l'âge minimum et l'âge maximum est inférieur à ce max.

== Exo 32

Spring s'occupe de la création du validator,
on peut y injecter le max-range depuis le fichier de configuration (custom.api.pets.max-range=100)

Utiliser un @Value pour le faire.

/!\ Dans ce contexte on ne peut pas utiliser lateinit.
Il faut fournir une valeur par défaut directement sur le champ.

== Exo 33

Ajouter dans le fichier src/main/resources/application.yml la configuration suivante

[source,yaml]
----
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
----

La base de données H2 est une base de données en mémoire.
Pour y accéder, il faut se rendre sur l'url http://localhost:8080/h2-console

A chaque démarrage de l'application, la base de données est réinitialisée.

Pour le constater vous pouvez lancer la requête suivante avant de relancer le service:

[source,sql]
----
CREATE TABLE TEST(ID INT PRIMARY KEY, NAME VARCHAR(255));
----

== Exo 34

Modifier le fichier src/main/resources/application.yml avec pour datasource.url jdbc:h2:file:./data/testdb

Les données sont stockées dans un fichier data/testdb.mv.db à la racine du projet.

Entre deux démarrages de l'application, les données sont conservées.

== Exo 35

Créer une Entity (au sens JPA) HumanEntity qui correspond aux attributs de HumanDto

Créer un repository HumanRepository qui étend JpaRepository

A l'aide de se repository, dans DatabaseProxy, implémentez les fonctions suivantes:

- saveHuman

- findHumanById

- findAllHumans

Le test `exo 35` doit passer.

== Exo 36

Modifier HumanDto pour lui ajouter un attribut contact

[source,kotlin]
----
data class HumanDto(val humanId: Int?, val name: String, val contact: ContactDto)
----

Créer une Entity (au sens JPA) ContactEntity qui correspond aux attributs de ContactDto.

A l'aide d'un @OneToOne, lier HumanEntity et ContactEntity de manière uni-directionnel
(ie on peut faire human.contact.email, mais pas contact.human.name)

Le test `exo 36` doit passer.

== Exo 37

Modifier le OneToOne pour qu'il soit bi-directionnel

Le test `exo 36` doit passer.

== Exo 38

Modifier HumanDto pour lui ajouter un attribut pets

[source,kotlin]
----
data class HumanDto(val humanId: Int?, val name: String, val contact: ContactDto, val pets: List<PetDto>)
----

Créer une Entity (au sens JPA) ContactEntity qui correspond aux attributs de PetDto.

A l'aide d'un @OneToMany, lier HumanEntity et ContactEntity de manière uni-directionnel

Le test `exo 38` doit passer.

== Exo 39

Modifier le OneToMany pour qu'il soit bi-directionnel

Le test `exo 38` doit passer.

== Exo 40

Ajouter un nouveau endpoint DELETE "/api/v1/humans/{humanId}/pets/{petId}" et les services requis.

Ce endpoint permet de supprimer un pet.

Le test `exo 40` doit passer.

== Exo Bonus

Créer une configuration application-postgres.yml où la base h2 est remplacé par par une base postgresql

Pour lancer une base postgres sur le port 5432, vous pouvez utiliser la commande suivante:
`podman run --name postgres -e POSTGRES_USER=username -e POSTGRES_PASSWORD=password -p 5432:5432 -v /tmp/data -d postgres`

== Exo 41

Ajouter spring securité au projet.

Configurer le SecurityFilterChain pour que toutes les requêtes GET passent sans authentification, mais que les autres requêtes nécessitent une authentification.

Le test `exo 41` doit passer.

== Exo 42

Appeler le endpoint DELETE "/api/v1/humans/{humanId}/pets/{petId}" nécessite d'avoir le rôle admin.

Modifier la configuration pour que le test `exo 40` ne passe plus à cause d'une erreur 403, puis corriger le test pour ne plus avoir une 403.

== Exo 43

Ajouter un InMemoryUserDetailsManager avec un utilisateur user classique et un utilisateur admin.

Une fois l'application lancé, appeler les endpoints (curl, bruno... ) avec le basic auth qui correspond à ces utilisateurs.

== Exo 44

Modifier HumanDto pour lui ajouter un attribut creatorLogin

[source,kotlin]
----
data class HumanDto(val humanId: Int?, val name: String, val contact: ContactDto, val pets: List<PetDto>, val creatorLogin: String?)
----

Ce Login doit être celui de l'utilisateur authentifié lors de la création de la donnée.

Le test `exo 44` doit passer une fois la linge MockUser activé.

== Exo Bonus

Remplacer le InMemoryUserDetailsManager par un JdbcUserDetailsManager.
