== Exo 41

Ajouter spring security au projet.

Configurer le SecurityFilterChain pour que toutes les requêtes GET passent sans authentification, mais que les autres requêtes nécessitent une authentification.

Le test `exo 41` doit passer.

== Exo 42

Appeler le endpoint DELETE "/api/v1/humans/{humanId}/pets/{petId}" nécessite d'avoir le rôle admin.

Modifier la configuration pour que le test `exo 40` ne passe plus à cause d'une erreur 403, puis corriger le test pour ne plus avoir une 403.

== Exo 43

Ajouter un InMemoryUserDetailsManager avec un utilisateur user classique et un utilisateur admin.

Une fois l'application lancée, appeler les endpoints (curl, bruno...) avec le basic auth qui correspond à ces utilisateurs.

== Exo 44

Modifier HumanDto pour lui ajouter un attribut creatorLogin

[source,kotlin]
----
data class HumanDto(val humanId: Int?, val name: String, val contact: ContactDto, val pets: List<PetDto>, val creatorLogin: String?)
----

Ce login doit être celui de l'utilisateur authentifié lors de la création de la donnée.

Le test `exo 44` doit passer une fois la ligne MockUser activée.

== Exo Bonus

Remplacer le InMemoryUserDetailsManager par un JdbcUserDetailsManager.

== Exo 45

WebClientService#hello pour appeler en GET l'url http://localhost:8888/api/v1/hello

Le web-service renvoi un objet de type HelloDto qui doit être retourné par la fonction.

Le test `exo 45` doit passer.

== Exo 46

Modifier la même méthode pour rajouter le query param `name=World` à l'url.

Le test `exo 46` doit passer.

== Exo 47

WebClientService#noHello pour appeler en POST l'url http://localhost:8888/api/v1/noHello
avec en Body HelloDto("No hello")

Le test `exo 47` doit passer.

== Exo 48

WebClientService#error pour appeler en GET l'url http://localhost:8888/api/v1/error

En cas de réponse 5xx, la méthode doit renvoyer une exception de type MyInternalError.

Le test `exo 48` doit passer.

== Exo 50 -> 53

Faire les exos 45 à 48 mais dans la classe RestClientService