spring.application.name: exo20
spring:
  r2dbc:
    url: jdbc:h2:mem:///test;MODE=PostgreSQL
  flyway:
    enabled: true
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
  h2:
    console:
      enabled: true

